language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # codechecker
  - sudo apt-get install -qq clang build-essential curl doxygen gcc-multilib git python-virtualenv python-dev thrift-compiler
  - ./build_codechecker

script: 
  - ./run_codechecker || true
