language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # codechecker
  - sudo apt-get install -qq clang build-essential curl doxygen gcc-multilib git python-virtualenv python-dev thrift-compiler
  - ./build_codechecker

script: 
  - ./run_codechecker || true
