#!/bin/bash

# Find thrift
source ~/codechecker/venv/bin/activate

# Add CodeChecker to path
export PATH=~/codechecker/build/CodeChecker/bin:$PATH

qmake

CodeChecker check --quiet --enable-all -b "make clean && make debug"

# CodeChecker check --quiet --enable-all -b "make clean && make debug" -o results
